spring:
  main:
    log-startup-info: true # выводим служебную информацию
    banner-mode: off       # не выводим баннер

logging.level:
  root: INFO
  ru.yandex.practicum.quiz: TRACE # настраиваем уровень логера

spring-quiz:
  report:
    mode: "concise"  # краткий режим отчёта